### PR TITLE
Changed grader to use the new grading system

### PR DESCRIPTION
**Pull request by andywot**
Modified the grader file and each utility file in each exercise for the new grading system. It should work just find as far as I can tell. This should fixed issue #81.

### CODE REVIEW

**Comment by Abhishek-michael** [comment]
its still not working
i clone the repository and ran the notebook and the grader gives the same error

**Comment by andywot** [comment]
> its still not working
> i clone the repository and ran the notebook and the grader gives the same error

did you clone my branch or the master branch? I just tested my grader by cloning my branch again and it's working. Make sure you use the correct token for the corresponding exercise. Can you send me the error if you're still getting one?

**Comment by moovit-gmbh** [comment]
> its still not working
> i clone the repository and ran the notebook and the grader gives the same error

Are you sure you are on the correct branch? It worked for me after:
cd ml-coursera-python-assignments
git fetch origin new-grader
git checkout new-grader

**Comment by HVossi92** [comment]
> its still not working
> i clone the repository and ran the notebook and the grader gives the same error

Are you sure you are on the correct branch? It worked for me after:
cd ml-coursera-python-assignments
git fetch origin new-grader
git checkout new-grader

**Comment by dibgerge** [comment]
Thank you for updating this!

**Comment by lohyenshen** [comment]
thanks, it worked for me

**Pull request merged**
